version: '3.8'

services:
  postgres:  # Your existing PostgreSQL service
    image: postgis/postgis:14-3.3
    environment:
      POSTGRES_USER: geescan
      POSTGRES_PASSWORD: geescan
      POSTGRES_DB: geescan
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/app/schema.sql:/docker-entrypoint-initdb.d/init.sql  # Mount your schema

  pgadmin:  # Your existing pgAdmin service
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@geescan.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data: