# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        self.central_widget = QtWidgets.QWidget(MainWindow)
        self.central_widget.setObjectName("central_widget")
        MainWindow.setCentralWidget(self.central_widget)
        self.main_layout = QtWidgets.QHBoxLayout(self.central_widget)
        self.main_layout.setContentsMargins(0, 0, 0, 0)
        self.main_layout.setSpacing(0)
        self.main_layout.setObjectName("main_layout")
        self.main_splitter = QtWidgets.QSplitter(self.central_widget)
        self.main_splitter.setOrientation(QtCore.Qt.Horizontal)
        self.main_splitter.setHandleWidth(2)
        self.main_splitter.setChildrenCollapsible(False)
        self.main_splitter.setObjectName("main_splitter")
        self.left_panel = QtWidgets.QGroupBox(self.main_splitter)
        self.left_panel.setTitle("Areas of Interest")
        self.left_panel.setObjectName("left_panel")
        self.left_layout = QtWidgets.QVBoxLayout(self.left_panel)
        self.left_layout.setSpacing(10)
        self.left_layout.setObjectName("left_layout")
        self.aoi_list = QtWidgets.QListWidget(self.left_panel)
        self.aoi_list.setObjectName("aoi_list")
        self.left_layout.addWidget(self.aoi_list)
        self.buttons_container = QtWidgets.QWidget(self.left_panel)
        self.buttons_container.setObjectName("buttons_container")
        self.buttons_layout = QtWidgets.QHBoxLayout(self.buttons_container)
        self.buttons_layout.setContentsMargins(0, 0, 0, 0)
        self.buttons_layout.setSpacing(6)
        self.buttons_layout.setObjectName("buttons_layout")
        self.buttons_layout.addStretch()
        self.add_aoi_button = QtWidgets.QPushButton(self.buttons_container)
        self.add_aoi_button.setMinimumWidth(80)
        self.add_aoi_button.setFixedHeight(30)
        self.add_aoi_button.setObjectName("add_aoi_button")
        self.buttons_layout.addWidget(self.add_aoi_button)
        self.import_aoi_button = QtWidgets.QPushButton(self.buttons_container)
        self.import_aoi_button.setMinimumWidth(80)
        self.import_aoi_button.setFixedHeight(30)
        self.import_aoi_button.setObjectName("import_aoi_button")
        self.buttons_layout.addWidget(self.import_aoi_button)
        self.delete_aoi_button = QtWidgets.QPushButton(self.buttons_container)
        self.delete_aoi_button.setMinimumWidth(80)
        self.delete_aoi_button.setFixedHeight(30)
        self.delete_aoi_button.setObjectName("delete_aoi_button")
        self.buttons_layout.addWidget(self.delete_aoi_button)
        self.buttons_layout.addStretch()
        self.left_layout.addWidget(self.buttons_container)
        self.map_container = QtWidgets.QGroupBox(self.main_splitter)
        self.map_container.setTitle("Map View")
        self.map_container.setObjectName("map_container")
        self.map_layout = QtWidgets.QVBoxLayout(self.map_container)
        self.map_layout.setContentsMargins(5, 5, 5, 5)
        self.map_layout.setObjectName("map_layout")
        self.right_panel = QtWidgets.QGroupBox(self.main_splitter)
        self.right_panel.setTitle("SAR Parameters")
        self.right_panel.setObjectName("right_panel")
        self.right_layout = QtWidgets.QVBoxLayout(self.right_panel)
        self.right_layout.setSpacing(10)
        self.right_layout.setObjectName("right_layout")
        self.main_layout.addWidget(self.main_splitter)
        self.main_splitter.setSizes([1000, 1000, 1000])
        MainWindow.setWindowTitle("SAR AOI Manager")
        self.add_aoi_button.setText("Add AOI")
        self.import_aoi_button.setText("Import")
        self.delete_aoi_button.setText("Delete")
        MainWindow.setStyleSheet("""
            QMainWindow, QWidget {
                background-color: #1e1e1e;
                color: #ffffff;
            }
            QGroupBox {
                font-weight: bold;
                border: 1px solid #3e3e42;
                border-radius: 3px;
                margin-top: 0.5em;
                padding-top: 0.5em;
            }
            QGroupBox::title {
                subcontrol-origin: margin;
                left: 10px;
                padding: 0 3px 0 3px;
            }
            QSplitter::handle {
                background-color: #2d2d2d;
            }
            QListWidget {
                background-color: #252526;
                border: 1px solid #3e3e42;
                border-radius: 4px;
            }
            QListWidget::item {
                padding: 4px;
            }
            QListWidget::item:selected {
                background-color: #0e639c;
            }
            QPushButton {
                background-color: #0e639c;
                border: none;
                border-radius: 4px;
                padding: 6px 12px;
                color: white;
                width: 80px;
            }
            QPushButton:hover {
                background-color: #1177bb;
            }
            QPushButton:pressed {
                background-color: #0d5289;
            }
            QLineEdit, QComboBox, QDateEdit {
                background-color: #3c3c3c;
                border: 1px solid #3e3e42;
                border-radius: 4px;
                padding: 4px;
                color: white;
            }
        """)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SAR AOI Manager"))
        self.add_aoi_button.setText(_translate("MainWindow", "Add AOI"))
        self.import_aoi_button.setText(_translate("MainWindow", "Import"))
        self.delete_aoi_button.setText(_translate("MainWindow", "Delete"))
